#ifndef GGIPANMASKPOSTDL_H
#define GGIPANMASKPOSTDL_H

#include "ultra64.h"
#include "global.h"

extern u64 gGiPanMaskPostDL_Postmans_Hat_texture0_ci8[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture0_pal_rgba16[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture1_ci8[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture1_pal_rgba16[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture2_ci8[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture2_pal_rgba16[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture3_ci8[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture3_pal_rgba16[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture4_ci8[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture4_pal_rgba16[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture5_ci8[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture5_pal_rgba16[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture6_ci8[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture6_pal_rgba16[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture7_ci8[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture7_pal_rgba16[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture8_ci8[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture8_pal_rgba16[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture9_ci8[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture9_pal_rgba16[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture10_ci8[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture10_pal_rgba16[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture11_ci8[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture11_pal_rgba16[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture12_ci8[];
extern u64 gGiPanMaskPostDL_Postmans_Hat_texture12_pal_rgba16[];
extern Vtx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_vtx_0[13];
extern Gfx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_tri_0[];
extern Vtx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_vtx_1[81];
extern Gfx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_tri_1[];
extern Vtx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_vtx_2[10];
extern Gfx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_tri_2[];
extern Vtx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_vtx_3[49];
extern Gfx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_tri_3[];
extern Vtx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_vtx_4[30];
extern Gfx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_tri_4[];
extern Vtx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_vtx_5[18];
extern Gfx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_tri_5[];
extern Vtx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_vtx_6[12];
extern Gfx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_tri_6[];
extern Vtx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_vtx_7[16];
extern Gfx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_tri_7[];
extern Vtx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_vtx_8[10];
extern Gfx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_tri_8[];
extern Vtx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_vtx_9[4];
extern Gfx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_tri_9[];
extern Vtx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_vtx_10[8];
extern Gfx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_tri_10[];
extern Vtx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_vtx_11[32];
extern Gfx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_tri_11[];
extern Vtx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_vtx_12[8];
extern Gfx gGiPanMaskPostDL_gGiPanMaskPostDL_mesh_layer_Opaque_tri_12[];
extern Gfx mat_gGiPanMaskPostDL_Postmans_Hat_mat_f3d_layerOpaque[];
extern Gfx mat_revert_gGiPanMaskPostDL_Postmans_Hat_mat_f3d_layerOpaque[];
extern Gfx mat_gGiPanMaskPostDL_Postmans_Hat_mat_001_f3d_layerOpaque[];
extern Gfx mat_revert_gGiPanMaskPostDL_Postmans_Hat_mat_001_f3d_layerOpaque[];
extern Gfx mat_gGiPanMaskPostDL_Postmans_Hat_mat_002_f3d_layerOpaque[];
extern Gfx mat_revert_gGiPanMaskPostDL_Postmans_Hat_mat_002_f3d_layerOpaque[];
extern Gfx mat_gGiPanMaskPostDL_Postmans_Hat_mat_003_f3d_layerOpaque[];
extern Gfx mat_revert_gGiPanMaskPostDL_Postmans_Hat_mat_003_f3d_layerOpaque[];
extern Gfx mat_gGiPanMaskPostDL_Postmans_Hat_mat_004_f3d_layerOpaque[];
extern Gfx mat_revert_gGiPanMaskPostDL_Postmans_Hat_mat_004_f3d_layerOpaque[];
extern Gfx mat_gGiPanMaskPostDL_Postmans_Hat_mat_005_f3d_layerOpaque[];
extern Gfx mat_revert_gGiPanMaskPostDL_Postmans_Hat_mat_005_f3d_layerOpaque[];
extern Gfx mat_gGiPanMaskPostDL_Postmans_Hat_mat_006_f3d_layerOpaque[];
extern Gfx mat_revert_gGiPanMaskPostDL_Postmans_Hat_mat_006_f3d_layerOpaque[];
extern Gfx mat_gGiPanMaskPostDL_Postmans_Hat_mat_007_f3d_layerOpaque[];
extern Gfx mat_revert_gGiPanMaskPostDL_Postmans_Hat_mat_007_f3d_layerOpaque[];
extern Gfx mat_gGiPanMaskPostDL_Postmans_Hat_mat_008_f3d_layerOpaque[];
extern Gfx mat_revert_gGiPanMaskPostDL_Postmans_Hat_mat_008_f3d_layerOpaque[];
extern Gfx mat_gGiPanMaskPostDL_Postmans_Hat_mat_009_f3d_layerOpaque[];
extern Gfx mat_revert_gGiPanMaskPostDL_Postmans_Hat_mat_009_f3d_layerOpaque[];
extern Gfx mat_gGiPanMaskPostDL_Postmans_Hat_mat_010_f3d_layerOpaque[];
extern Gfx mat_revert_gGiPanMaskPostDL_Postmans_Hat_mat_010_f3d_layerOpaque[];
extern Gfx mat_gGiPanMaskPostDL_Postmans_Hat_mat_011_f3d_layerOpaque[];
extern Gfx mat_revert_gGiPanMaskPostDL_Postmans_Hat_mat_011_f3d_layerOpaque[];
extern Gfx mat_gGiPanMaskPostDL_Postmans_Hat_mat_012_f3d_layerOpaque[];
extern Gfx mat_revert_gGiPanMaskPostDL_Postmans_Hat_mat_012_f3d_layerOpaque[];
extern Gfx gGiPanMaskPostDL[];

#endif
