#ifndef GLINKHUMANHOOKSHOTDL_MESH_H
#define GLINKHUMANHOOKSHOTDL_MESH_H

#include "ultra64.h"
#include "global.h"

extern u64 gLinkHumanHookshotDL_mesh_tex_01B380_ci8_png_003_ci8[];
extern u64 gLinkHumanHookshotDL_mesh_tex_01B380_ci8_png_003_pal_rgba16[];
extern u64 gLinkHumanHookshotDL_mesh_tex_01A280_ci8_png_004_ci8[];
extern u64 gLinkHumanHookshotDL_mesh_tex_01A280_ci8_png_004_pal_rgba16[];
extern u64 gLinkHumanHookshotDL_mesh_tex_019A80_ci8_png_004_ci8[];
extern u64 gLinkHumanHookshotDL_mesh_tex_019A80_ci8_png_004_pal_rgba16[];
extern Vtx gLinkHumanHookshotDL_mesh_gLinkHumanHookshotDL_mesh_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gLinkHumanHookshotDL_mesh_gLinkHumanHookshotDL_mesh_mesh_layer_Opaque_vtx_0[58];
extern Gfx gLinkHumanHookshotDL_mesh_gLinkHumanHookshotDL_mesh_mesh_layer_Opaque_tri_0[];
extern Vtx gLinkHumanHookshotDL_mesh_gLinkHumanHookshotDL_mesh_mesh_layer_Opaque_vtx_1[18];
extern Gfx gLinkHumanHookshotDL_mesh_gLinkHumanHookshotDL_mesh_mesh_layer_Opaque_tri_1[];
extern Vtx gLinkHumanHookshotDL_mesh_gLinkHumanHookshotDL_mesh_mesh_layer_Opaque_vtx_2[3];
extern Gfx gLinkHumanHookshotDL_mesh_gLinkHumanHookshotDL_mesh_mesh_layer_Opaque_tri_2[];
extern Vtx gLinkHumanHookshotDL_mesh_gLinkHumanHookshotDL_mesh_mesh_layer_Opaque_vtx_3[3];
extern Gfx gLinkHumanHookshotDL_mesh_gLinkHumanHookshotDL_mesh_mesh_layer_Opaque_tri_3[];
extern Vtx gLinkHumanHookshotDL_mesh_gLinkHumanHookshotDL_mesh_mesh_layer_Opaque_vtx_4[3];
extern Gfx gLinkHumanHookshotDL_mesh_gLinkHumanHookshotDL_mesh_mesh_layer_Opaque_tri_4[];
extern Vtx gLinkHumanHookshotDL_mesh_gLinkHumanHookshotDL_mesh_mesh_layer_Opaque_vtx_5[9];
extern Gfx gLinkHumanHookshotDL_mesh_gLinkHumanHookshotDL_mesh_mesh_layer_Opaque_tri_5[];
extern Vtx gLinkHumanHookshotDL_mesh_gLinkHumanHookshotDL_mesh_mesh_layer_Opaque_vtx_6[96];
extern Gfx gLinkHumanHookshotDL_mesh_gLinkHumanHookshotDL_mesh_mesh_layer_Opaque_tri_6[];
extern Gfx mat_gLinkHumanHookshotDL_mesh_f3dlite_material_146_layerOpaque[];
extern Gfx mat_revert_gLinkHumanHookshotDL_mesh_f3dlite_material_146_layerOpaque[];
extern Gfx mat_gLinkHumanHookshotDL_mesh_f3dlite_material_147_layerOpaque[];
extern Gfx mat_revert_gLinkHumanHookshotDL_mesh_f3dlite_material_147_layerOpaque[];
extern Gfx mat_gLinkHumanHookshotDL_mesh_f3dlite_material_148_layerOpaque[];
extern Gfx mat_revert_gLinkHumanHookshotDL_mesh_f3dlite_material_148_layerOpaque[];
extern Gfx mat_gLinkHumanHookshotDL_mesh_f3dlite_material_149_layerOpaque[];
extern Gfx mat_revert_gLinkHumanHookshotDL_mesh_f3dlite_material_149_layerOpaque[];
extern Gfx mat_gLinkHumanHookshotDL_mesh_f3dlite_material_150_layerOpaque[];
extern Gfx mat_revert_gLinkHumanHookshotDL_mesh_f3dlite_material_150_layerOpaque[];
extern Gfx mat_gLinkHumanHookshotDL_mesh_f3dlite_material_151_layerOpaque[];
extern Gfx mat_revert_gLinkHumanHookshotDL_mesh_f3dlite_material_151_layerOpaque[];
extern Gfx mat_gLinkHumanHookshotDL_mesh_f3dlite_material_152_layerOpaque[];
extern Gfx mat_revert_gLinkHumanHookshotDL_mesh_f3dlite_material_152_layerOpaque[];
extern Gfx gLinkHumanHookshotDL_mesh[];

#endif
