#ifndef GPANSWORD1HILTDL_H
#define GPANSWORD1HILTDL_H

#include "ultra64.h"
#include "global.h"

extern u64 gPanSword1HiltDL_swordfix_texture0_ci8[];
extern u64 gPanSword1HiltDL_swordfix_texture0_pal_rgba16[];
extern u64 gPanSword1HiltDL_swordfix_texture1_ci8[];
extern u64 gPanSword1HiltDL_swordfix_texture1_pal_rgba16[];
extern u64 gPanSword1HiltDL_swordfix_texture2_ci8[];
extern u64 gPanSword1HiltDL_swordfix_texture2_pal_rgba16[];
extern u64 gPanSword1HiltDL_swordfix_texture3_ci8[];
extern u64 gPanSword1HiltDL_swordfix_texture3_pal_rgba16[];
extern u64 gPanSword1HiltDL_swordfix_texture4_ci8[];
extern u64 gPanSword1HiltDL_swordfix_texture4_pal_rgba16[];
extern u64 gPanSword1HiltDL_swordfix_texture5_ci8[];
extern u64 gPanSword1HiltDL_swordfix_texture5_pal_rgba16[];
extern u64 gPanSword1HiltDL_swordfix_texture6_ci8[];
extern u64 gPanSword1HiltDL_swordfix_texture6_pal_rgba16[];
extern u64 gPanSword1HiltDL_swordfix_texture7_ci8[];
extern u64 gPanSword1HiltDL_swordfix_texture7_pal_rgba16[];
extern u64 gPanSword1HiltDL_swordfix_texture8_ci8[];
extern u64 gPanSword1HiltDL_swordfix_texture8_pal_rgba16[];
extern u64 gPanSword1HiltDL_swordfix_texture9_ci8[];
extern u64 gPanSword1HiltDL_swordfix_texture9_pal_rgba16[];
extern Vtx gPanSword1HiltDL_gPanSword1HiltDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gPanSword1HiltDL_gPanSword1HiltDL_mesh_layer_Opaque_vtx_0[6];
extern Gfx gPanSword1HiltDL_gPanSword1HiltDL_mesh_layer_Opaque_tri_0[];
extern Vtx gPanSword1HiltDL_gPanSword1HiltDL_mesh_layer_Opaque_vtx_1[12];
extern Gfx gPanSword1HiltDL_gPanSword1HiltDL_mesh_layer_Opaque_tri_1[];
extern Vtx gPanSword1HiltDL_gPanSword1HiltDL_mesh_layer_Opaque_vtx_2[20];
extern Gfx gPanSword1HiltDL_gPanSword1HiltDL_mesh_layer_Opaque_tri_2[];
extern Vtx gPanSword1HiltDL_gPanSword1HiltDL_mesh_layer_Opaque_vtx_3[18];
extern Gfx gPanSword1HiltDL_gPanSword1HiltDL_mesh_layer_Opaque_tri_3[];
extern Vtx gPanSword1HiltDL_gPanSword1HiltDL_mesh_layer_Opaque_vtx_4[12];
extern Gfx gPanSword1HiltDL_gPanSword1HiltDL_mesh_layer_Opaque_tri_4[];
extern Vtx gPanSword1HiltDL_gPanSword1HiltDL_mesh_layer_Opaque_vtx_5[16];
extern Gfx gPanSword1HiltDL_gPanSword1HiltDL_mesh_layer_Opaque_tri_5[];
extern Vtx gPanSword1HiltDL_gPanSword1HiltDL_mesh_layer_Opaque_vtx_6[10];
extern Gfx gPanSword1HiltDL_gPanSword1HiltDL_mesh_layer_Opaque_tri_6[];
extern Vtx gPanSword1HiltDL_gPanSword1HiltDL_mesh_layer_Opaque_vtx_7[6];
extern Gfx gPanSword1HiltDL_gPanSword1HiltDL_mesh_layer_Opaque_tri_7[];
extern Vtx gPanSword1HiltDL_gPanSword1HiltDL_mesh_layer_Opaque_vtx_8[6];
extern Gfx gPanSword1HiltDL_gPanSword1HiltDL_mesh_layer_Opaque_tri_8[];
extern Vtx gPanSword1HiltDL_gPanSword1HiltDL_mesh_layer_Opaque_vtx_9[6];
extern Gfx gPanSword1HiltDL_gPanSword1HiltDL_mesh_layer_Opaque_tri_9[];
extern Gfx mat_gPanSword1HiltDL_swordfix_mat_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword1HiltDL_swordfix_mat_f3d_layerOpaque[];
extern Gfx mat_gPanSword1HiltDL_swordfix_mat_001_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword1HiltDL_swordfix_mat_001_f3d_layerOpaque[];
extern Gfx mat_gPanSword1HiltDL_swordfix_mat_002_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword1HiltDL_swordfix_mat_002_f3d_layerOpaque[];
extern Gfx mat_gPanSword1HiltDL_swordfix_mat_003_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword1HiltDL_swordfix_mat_003_f3d_layerOpaque[];
extern Gfx mat_gPanSword1HiltDL_swordfix_mat_004_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword1HiltDL_swordfix_mat_004_f3d_layerOpaque[];
extern Gfx mat_gPanSword1HiltDL_swordfix_mat_005_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword1HiltDL_swordfix_mat_005_f3d_layerOpaque[];
extern Gfx mat_gPanSword1HiltDL_swordfix_mat_006_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword1HiltDL_swordfix_mat_006_f3d_layerOpaque[];
extern Gfx mat_gPanSword1HiltDL_swordfix_mat_007_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword1HiltDL_swordfix_mat_007_f3d_layerOpaque[];
extern Gfx mat_gPanSword1HiltDL_swordfix_mat_008_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword1HiltDL_swordfix_mat_008_f3d_layerOpaque[];
extern Gfx mat_gPanSword1HiltDL_swordfix_mat_009_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword1HiltDL_swordfix_mat_009_f3d_layerOpaque[];
extern Gfx gPanSword1HiltDL[];

#endif
