#ifndef GPANSWORD4HILTDL_H
#define GPANSWORD4HILTDL_H

#include "ultra64.h"
#include "global.h"

extern u64 gPanSword4HiltDL__2HSword_texture4_ci8[];
extern u64 gPanSword4HiltDL__2HSword_texture4_pal_rgba16[];
extern u64 gPanSword4HiltDL__2HSword_texture5_ci8[];
extern u64 gPanSword4HiltDL__2HSword_texture5_pal_rgba16[];
extern u64 gPanSword4HiltDL__2HSword_texture6_ci8[];
extern u64 gPanSword4HiltDL__2HSword_texture6_pal_rgba16[];
extern u64 gPanSword4HiltDL__2HSword_texture7_ci8[];
extern u64 gPanSword4HiltDL__2HSword_texture7_pal_rgba16[];
extern u64 gPanSword4HiltDL__2HSword_texture8_ci8[];
extern u64 gPanSword4HiltDL__2HSword_texture8_pal_rgba16[];
extern u64 gPanSword4HiltDL__2HSword_texture9_ci8[];
extern u64 gPanSword4HiltDL__2HSword_texture9_pal_rgba16[];
extern u64 gPanSword4HiltDL__2HSword_texture10_ci8[];
extern u64 gPanSword4HiltDL__2HSword_texture10_pal_rgba16[];
extern u64 gPanSword4HiltDL__2HSword_texture11_ci8[];
extern u64 gPanSword4HiltDL__2HSword_texture11_pal_rgba16[];
extern u64 gPanSword4HiltDL__2HSword_texture13_ci8[];
extern u64 gPanSword4HiltDL__2HSword_texture13_pal_rgba16[];
extern u64 gPanSword4HiltDL__2HSword_texture14_ci8[];
extern u64 gPanSword4HiltDL__2HSword_texture14_pal_rgba16[];
extern u64 gPanSword4HiltDL__2HSword_hilt_texture0_ci8[];
extern u64 gPanSword4HiltDL__2HSword_hilt_texture0_pal_rgba16[];
extern u64 gPanSword4HiltDL__2HSword_hilt_texture1_ci8[];
extern u64 gPanSword4HiltDL__2HSword_hilt_texture1_pal_rgba16[];
extern Vtx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_vtx_0[32];
extern Gfx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_tri_0[];
extern Vtx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_vtx_1[23];
extern Gfx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_tri_1[];
extern Vtx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_vtx_2[20];
extern Gfx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_tri_2[];
extern Vtx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_vtx_3[12];
extern Gfx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_tri_3[];
extern Vtx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_vtx_4[12];
extern Gfx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_tri_4[];
extern Vtx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_vtx_5[12];
extern Gfx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_tri_5[];
extern Vtx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_vtx_6[5];
extern Gfx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_tri_6[];
extern Vtx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_vtx_7[6];
extern Gfx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_tri_7[];
extern Vtx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_vtx_8[16];
extern Gfx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_tri_8[];
extern Vtx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_vtx_9[9];
extern Gfx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_tri_9[];
extern Vtx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_vtx_10[18];
extern Gfx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_tri_10[];
extern Vtx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_vtx_11[12];
extern Gfx gPanSword4HiltDL_gPanSword4HiltDL_mesh_layer_Opaque_tri_11[];
extern Gfx mat_gPanSword4HiltDL__2HSword_mat_004_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword4HiltDL__2HSword_mat_004_f3d_layerOpaque[];
extern Gfx mat_gPanSword4HiltDL__2HSword_mat_005_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword4HiltDL__2HSword_mat_005_f3d_layerOpaque[];
extern Gfx mat_gPanSword4HiltDL__2HSword_mat_006_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword4HiltDL__2HSword_mat_006_f3d_layerOpaque[];
extern Gfx mat_gPanSword4HiltDL__2HSword_mat_007_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword4HiltDL__2HSword_mat_007_f3d_layerOpaque[];
extern Gfx mat_gPanSword4HiltDL__2HSword_mat_008_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword4HiltDL__2HSword_mat_008_f3d_layerOpaque[];
extern Gfx mat_gPanSword4HiltDL__2HSword_mat_009_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword4HiltDL__2HSword_mat_009_f3d_layerOpaque[];
extern Gfx mat_gPanSword4HiltDL__2HSword_mat_010_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword4HiltDL__2HSword_mat_010_f3d_layerOpaque[];
extern Gfx mat_gPanSword4HiltDL__2HSword_mat_011_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword4HiltDL__2HSword_mat_011_f3d_layerOpaque[];
extern Gfx mat_gPanSword4HiltDL__2HSword_mat_013_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword4HiltDL__2HSword_mat_013_f3d_layerOpaque[];
extern Gfx mat_gPanSword4HiltDL__2HSword_mat_014_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword4HiltDL__2HSword_mat_014_f3d_layerOpaque[];
extern Gfx mat_gPanSword4HiltDL__2HSword_hilt_mat_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword4HiltDL__2HSword_hilt_mat_f3d_layerOpaque[];
extern Gfx mat_gPanSword4HiltDL__2HSword_hilt_mat_001_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword4HiltDL__2HSword_hilt_mat_001_f3d_layerOpaque[];
extern Gfx gPanSword4HiltDL[];

#endif
