#ifndef GPANSWORD4BLADEDL_H
#define GPANSWORD4BLADEDL_H

#include "ultra64.h"
#include "global.h"

extern u64 gPanSword4BladeDL__2HSword_texture0_ci8[];
extern u64 gPanSword4BladeDL__2HSword_texture0_pal_rgba16[];
extern u64 gPanSword4BladeDL__2HSword_texture1_ci8[];
extern u64 gPanSword4BladeDL__2HSword_texture1_pal_rgba16[];
extern u64 gPanSword4BladeDL__2HSword_texture2_ci8[];
extern u64 gPanSword4BladeDL__2HSword_texture2_pal_rgba16[];
extern u64 gPanSword4BladeDL__2HSword_texture3_ci8[];
extern u64 gPanSword4BladeDL__2HSword_texture3_pal_rgba16[];
extern u64 gPanSword4BladeDL__2HSword_texture12_ci8[];
extern u64 gPanSword4BladeDL__2HSword_texture12_pal_rgba16[];
extern u64 gPanSword4BladeDL_white_silver_rgba32[];
extern Vtx gPanSword4BladeDL_gPanSword4BladeDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gPanSword4BladeDL_gPanSword4BladeDL_mesh_layer_Opaque_vtx_0[29];
extern Gfx gPanSword4BladeDL_gPanSword4BladeDL_mesh_layer_Opaque_tri_0[];
extern Vtx gPanSword4BladeDL_gPanSword4BladeDL_mesh_layer_Opaque_vtx_1[16];
extern Gfx gPanSword4BladeDL_gPanSword4BladeDL_mesh_layer_Opaque_tri_1[];
extern Vtx gPanSword4BladeDL_gPanSword4BladeDL_mesh_layer_Opaque_vtx_2[37];
extern Gfx gPanSword4BladeDL_gPanSword4BladeDL_mesh_layer_Opaque_tri_2[];
extern Vtx gPanSword4BladeDL_gPanSword4BladeDL_mesh_layer_Opaque_vtx_3[11];
extern Gfx gPanSword4BladeDL_gPanSword4BladeDL_mesh_layer_Opaque_tri_3[];
extern Vtx gPanSword4BladeDL_gPanSword4BladeDL_mesh_layer_Opaque_vtx_4[8];
extern Gfx gPanSword4BladeDL_gPanSword4BladeDL_mesh_layer_Opaque_tri_4[];
extern Vtx gPanSword4BladeDL_gPanSword4BladeDL_mesh_layer_Opaque_vtx_5[16];
extern Gfx gPanSword4BladeDL_gPanSword4BladeDL_mesh_layer_Opaque_tri_5[];
extern Gfx mat_gPanSword4BladeDL__2HSword_mat_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword4BladeDL__2HSword_mat_f3d_layerOpaque[];
extern Gfx mat_gPanSword4BladeDL__2HSword_mat_001_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword4BladeDL__2HSword_mat_001_f3d_layerOpaque[];
extern Gfx mat_gPanSword4BladeDL__2HSword_mat_002_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword4BladeDL__2HSword_mat_002_f3d_layerOpaque[];
extern Gfx mat_gPanSword4BladeDL__2HSword_mat_003_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword4BladeDL__2HSword_mat_003_f3d_layerOpaque[];
extern Gfx mat_gPanSword4BladeDL__2HSword_mat_012_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSword4BladeDL__2HSword_mat_012_f3d_layerOpaque[];
extern Gfx mat_gPanSword4BladeDL_metal_silver_layerOpaque[];
extern Gfx mat_revert_gPanSword4BladeDL_metal_silver_layerOpaque[];
extern Gfx gPanSword4BladeDL[];

#endif
