#ifndef GPANSHEATH3DL_H
#define GPANSHEATH3DL_H

#include "ultra64.h"
#include "global.h"

extern u64 gPanSheath3DL_Sheathe3_texture0_ci8[];
extern u64 gPanSheath3DL_Sheathe3_texture0_pal_rgba16[];
extern u64 gPanSheath3DL_Sheathe3_texture1_ci8[];
extern u64 gPanSheath3DL_Sheathe3_texture1_pal_rgba16[];
extern u64 gPanSheath3DL_Sheathe3_texture2_ci8[];
extern u64 gPanSheath3DL_Sheathe3_texture2_pal_rgba16[];
extern u64 gPanSheath3DL_Sheathe3_texture3_ci8[];
extern u64 gPanSheath3DL_Sheathe3_texture3_pal_rgba16[];
extern u64 gPanSheath3DL_Sheathe3_texture4_ci8[];
extern u64 gPanSheath3DL_Sheathe3_texture4_pal_rgba16[];
extern u64 gPanSheath3DL_Sheathe3_texture5_ci8[];
extern u64 gPanSheath3DL_Sheathe3_texture5_pal_rgba16[];
extern u64 gPanSheath3DL_Sheathe3_texture6_ci8[];
extern u64 gPanSheath3DL_Sheathe3_texture6_pal_rgba16[];
extern u64 gPanSheath3DL_Sheathe3_texture7_ci8[];
extern u64 gPanSheath3DL_Sheathe3_texture7_pal_rgba16[];
extern u64 gPanSheath3DL_Sheathe3_texture8_ci8[];
extern u64 gPanSheath3DL_Sheathe3_texture8_pal_rgba16[];
extern u64 gPanSheath3DL_Sheathe3_texture9_ci8[];
extern u64 gPanSheath3DL_Sheathe3_texture9_pal_rgba16[];
extern u64 gPanSheath3DL_Sheathe3_texture10_ci8[];
extern u64 gPanSheath3DL_Sheathe3_texture10_pal_rgba16[];
extern Vtx gPanSheath3DL_gPanSheath3DL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gPanSheath3DL_gPanSheath3DL_mesh_layer_Opaque_vtx_0[8];
extern Gfx gPanSheath3DL_gPanSheath3DL_mesh_layer_Opaque_tri_0[];
extern Vtx gPanSheath3DL_gPanSheath3DL_mesh_layer_Opaque_vtx_1[8];
extern Gfx gPanSheath3DL_gPanSheath3DL_mesh_layer_Opaque_tri_1[];
extern Vtx gPanSheath3DL_gPanSheath3DL_mesh_layer_Opaque_vtx_2[18];
extern Gfx gPanSheath3DL_gPanSheath3DL_mesh_layer_Opaque_tri_2[];
extern Vtx gPanSheath3DL_gPanSheath3DL_mesh_layer_Opaque_vtx_3[18];
extern Gfx gPanSheath3DL_gPanSheath3DL_mesh_layer_Opaque_tri_3[];
extern Vtx gPanSheath3DL_gPanSheath3DL_mesh_layer_Opaque_vtx_4[9];
extern Gfx gPanSheath3DL_gPanSheath3DL_mesh_layer_Opaque_tri_4[];
extern Vtx gPanSheath3DL_gPanSheath3DL_mesh_layer_Opaque_vtx_5[7];
extern Gfx gPanSheath3DL_gPanSheath3DL_mesh_layer_Opaque_tri_5[];
extern Vtx gPanSheath3DL_gPanSheath3DL_mesh_layer_Opaque_vtx_6[16];
extern Gfx gPanSheath3DL_gPanSheath3DL_mesh_layer_Opaque_tri_6[];
extern Vtx gPanSheath3DL_gPanSheath3DL_mesh_layer_Opaque_vtx_7[6];
extern Gfx gPanSheath3DL_gPanSheath3DL_mesh_layer_Opaque_tri_7[];
extern Vtx gPanSheath3DL_gPanSheath3DL_mesh_layer_Opaque_vtx_8[6];
extern Gfx gPanSheath3DL_gPanSheath3DL_mesh_layer_Opaque_tri_8[];
extern Vtx gPanSheath3DL_gPanSheath3DL_mesh_layer_Opaque_vtx_9[22];
extern Gfx gPanSheath3DL_gPanSheath3DL_mesh_layer_Opaque_tri_9[];
extern Vtx gPanSheath3DL_gPanSheath3DL_mesh_layer_Opaque_vtx_10[10];
extern Gfx gPanSheath3DL_gPanSheath3DL_mesh_layer_Opaque_tri_10[];
extern Gfx mat_gPanSheath3DL_Sheathe3_mat_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSheath3DL_Sheathe3_mat_f3d_layerOpaque[];
extern Gfx mat_gPanSheath3DL_Sheathe3_mat_001_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSheath3DL_Sheathe3_mat_001_f3d_layerOpaque[];
extern Gfx mat_gPanSheath3DL_Sheathe3_mat_002_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSheath3DL_Sheathe3_mat_002_f3d_layerOpaque[];
extern Gfx mat_gPanSheath3DL_Sheathe3_mat_003_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSheath3DL_Sheathe3_mat_003_f3d_layerOpaque[];
extern Gfx mat_gPanSheath3DL_Sheathe3_mat_004_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSheath3DL_Sheathe3_mat_004_f3d_layerOpaque[];
extern Gfx mat_gPanSheath3DL_Sheathe3_mat_005_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSheath3DL_Sheathe3_mat_005_f3d_layerOpaque[];
extern Gfx mat_gPanSheath3DL_Sheathe3_mat_006_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSheath3DL_Sheathe3_mat_006_f3d_layerOpaque[];
extern Gfx mat_gPanSheath3DL_Sheathe3_mat_007_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSheath3DL_Sheathe3_mat_007_f3d_layerOpaque[];
extern Gfx mat_gPanSheath3DL_Sheathe3_mat_008_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSheath3DL_Sheathe3_mat_008_f3d_layerOpaque[];
extern Gfx mat_gPanSheath3DL_Sheathe3_mat_009_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSheath3DL_Sheathe3_mat_009_f3d_layerOpaque[];
extern Gfx mat_gPanSheath3DL_Sheathe3_mat_010_f3d_layerOpaque[];
extern Gfx mat_revert_gPanSheath3DL_Sheathe3_mat_010_f3d_layerOpaque[];
extern Gfx gPanSheath3DL[];

#endif
